--- #YAML:1.0
name:               Sys-Lastlog
version:            1.6
abstract:           Provide a moderately Object Oreiented Interface to lastlog 
author:
    - jns@gellyfish.com
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
