#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sys-Lastlog
version:      1.4
version_from: Lastlog.pm
installdirs:  site
requires:
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
